# Generated by Django 4.0.8 on 2022-11-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='caractere',
            field=models.TextField(default='caractere'),
            preserve_default=False,
        ),
    ]
