# Generated by Django 4.0.8 on 2022-11-21 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0002_project_caractere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='caractere',
        ),
    ]
