# Generated by Django 4.0.8 on 2022-12-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0003_remove_project_caractere'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.TextField(default='to do; in progress; done', max_length=100),
            preserve_default=False,
        ),
    ]
