# Generated by Django 4.0.8 on 2022-12-03 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0011_groupofcollaborators'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupOfCollaborators',
        ),
    ]
