# Generated by Django 4.0.8 on 2022-12-03 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0013_groupofcollaborators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupofcollaborators',
            name='collaborators',
        ),
    ]
