# Generated by Django 4.0.8 on 2022-12-03 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0015_remove_groupofcollaborators_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupOfCollaborators',
        ),
    ]
