# Generated by Django 4.0.8 on 2022-12-03 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0016_delete_groupofcollaborators'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOfCollaborators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manager_app.project')),
            ],
        ),
    ]
