# Generated by Django 4.0.8 on 2022-12-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0017_groupofcollaborators'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='collaborators',
            field=models.CharField(default='isma; nono', max_length=100),
            preserve_default=False,
        ),
    ]
