# Generated by Django 4.0.8 on 2022-12-13 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0018_project_collaborators'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupOfCollaborators',
        ),
    ]
