# Generated by Django 4.0.8 on 2022-12-13 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0019_delete_groupofcollaborators'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_task', models.CharField(max_length=100)),
                ('assign_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assign_to', to='manager_app.project')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_app.project')),
            ],
        ),
    ]
