# Generated by Django 4.0.8 on 2022-12-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0020_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assign_to',
            field=models.CharField(max_length=100),
        ),
    ]
