# Generated by Django 4.0.8 on 2022-12-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0021_alter_task_assign_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status_task',
            field=models.CharField(default='no status', max_length=100),
        ),
    ]
