# Generated by Django 4.0.8 on 2022-12-31 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0022_task_status_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_sub_task', models.CharField(max_length=100)),
                ('assign_to', models.CharField(max_length=100)),
                ('status_sub_task', models.CharField(default='no status', max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_app.project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_app.task')),
            ],
        ),
    ]
