# Generated by Django 4.0.8 on 2023-01-05 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0023_subtask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubTask',
        ),
    ]
